name: Deploy Render Prod
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  deploy:
    uses: ./.github/workflows/render-deploy.yml
    with:
      environment: prod
      ref: ${{ github.sha }}
      polling-interval: "30000"
    secrets: inherit

  create-release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      # Create a release tag if the current ref is not a tag
      - name: Create Release Tag
        if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
        id: release-tag
        uses: skyfire-xyz/github-actions/create-release-tag@main
        with:
          ref: ${{ github.sha }}
      - name: Create Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-tag.outputs.tag-name }}
          generate_release_notes: true

      # Create a release if the current ref is a tag
      - name: Create Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/') == true }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
